# Generated by Django 3.0.8 on 2020-07-09 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
